# -*- coding: utf-8 -*-
"""
InfoCenter 中的全局费用、费率与规则常量（用于财报/成本核算）。

决策字段见 purchase / operation / sales；财报与 KPI 变量见 global.py
"""

from typing import Final

# --- 项目/合作年费 (€/年) ---
COST_VMI_PER_YEAR: Final[float] = 5_000.0
COST_SUPPLIER_DEVELOPMENT_PER_SUPPLIER_PER_YEAR: Final[float] = 60_000.0
COST_DUAL_SOURCE_PER_SUPPLIER_PER_YEAR: Final[float] = 40_000.0
COST_TRACK_AND_TRACE_PER_YEAR: Final[float] = 10_000.0
COST_QUARANTINE_PER_YEAR: Final[float] = 5_000.0
COST_SMED_PER_YEAR: Final[float] = 20_000.0
COST_OPTIMIZE_BOTTLING_SPEED_PER_YEAR: Final[float] = 30_000.0
COST_INFLATE_PET_MODULE_PER_YEAR: Final[float] = 140_000.0
COST_MCC_PER_YEAR: Final[float] = 10_000.0
COST_POOL_WORKFORCE_TRAINING_PER_EMPLOYEE_PER_ROUND: Final[float] = 1_000.0
COST_SOLVING_BREAKDOWNS_TRAINING_PER_EMPLOYEE: Final[float] = 400.0

# --- 投资 (€) ---
INVESTMENT_BUILDING: Final[float] = 2_500_000.0
INVESTMENT_INFLATE_PET_MODULE: Final[float] = 700_000.0

# --- 人力 ---
COST_FTE_PER_YEAR: Final[float] = 40_000.0
COST_FLEXIBLE_LABOR_PER_HOUR: Final[float] = 42.0
HOURS_PER_FTE_PER_WEEK: Final[int] = 40

# --- 仓储 ---
COST_PALLET_LOCATION_PER_YEAR: Final[float] = 200.0
COST_OVERFLOW_PALLET_PER_DAY: Final[float] = 3.0
COST_TANK_PER_YEAR: Final[float] = 4_000.0

# --- 外包罐区 PulpStore (€) ---
COST_OUTSOURCE_TANK_PER_DAY: Final[float] = 25.0
COST_OUTSOURCE_TANK_INTAKE_PER_DELIVERY: Final[float] = 10.0
COST_OUTSOURCE_TANK_DELIVERY_TO_TFC: Final[float] = 100.0

# --- 外包成品仓 (€) ---
COST_OUTSOURCE_FG_CONVENTIONAL_PALLET_PER_DAY: Final[float] = 1.30
COST_OUTSOURCE_FG_CONVENTIONAL_INTAKE_PER_PALLET: Final[float] = 1.25
COST_OUTSOURCE_FG_CONVENTIONAL_DISPATCH_PER_ORDER_LINE: Final[float] = 3.00
COST_OUTSOURCE_FG_AUTOMATED_PALLET_PER_DAY: Final[float] = 1.50
COST_OUTSOURCE_FG_AUTOMATED_INTAKE_PER_PALLET: Final[float] = 1.00
COST_OUTSOURCE_FG_AUTOMATED_DISPATCH_PER_ORDER_LINE: Final[float] = 2.50
COST_DESTROY_OBSOLETE_BATCH: Final[float] = 2.50

# --- 行政/订单处理 (€) ---
COST_INBOUND_ORDER: Final[float] = 50.0
COST_INBOUND_ORDER_LINE: Final[float] = 10.0
COST_OUTBOUND_ORDER: Final[float] = 25.0
COST_OUTBOUND_ORDER_LINE: Final[float] = 2.0
COST_CONTRACTED_SUPPLIER_ADMIN_PER_YEAR: Final[float] = 40_000.0

# --- 资金成本与利率 ---
INTEREST_RATE_PER_ANNUM: Final[float] = 0.15

# --- 物流 ---
EXPRESS_SHIPPING_KM_PER_DAY: Final[int] = 600

# --- 维护/技改效果（比例） ---
PREVENTIVE_MAINTENANCE_MINIMAL_HOURS_PER_LINE_PER_WEEK: Final[int] = 1
PREVENTIVE_MAINTENANCE_EXTENSIVE_HOURS_PER_LINE_PER_WEEK: Final[int] = 3
PREVENTIVE_MAINTENANCE_MINIMAL_BREAKDOWN_REDUCTION: Final[float] = 0.30
PREVENTIVE_MAINTENANCE_EXTENSIVE_BREAKDOWN_REDUCTION: Final[float] = 0.50
SOLVING_BREAKDOWNS_DURATION_REDUCTION: Final[float] = 0.40
SMED_CHANGEOVER_TIME_REDUCTION: Final[float] = 0.30
OPTIMIZE_BOTTLING_SPEED_INCREASE: Final[float] = 0.10

# --- 入库检验 ---
RAW_MATERIALS_INSPECTION_EXTRA_HOURS_PER_ORDER_LINE: Final[int] = 2

# --- 仿真周期 ---
WORKING_DAYS_PER_WEEK: Final[int] = 5
ROUND_DURATION_MONTHS: Final[int] = 6
