# ！/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time: 2026/5/20 21:58
# @Author: 朱阅澎
from typing import TypedDict


class SupplierInfo(TypedDict):
    """单条供应商记录的结构（字段名与含义）。"""
    name: str
    product_range: str
    country: str
    market_share: float          # 全球市场份额（%），如 2.0 表示 2.0%
    start_payment_term: str      # 如 "When ordering"
    lead_time: int               # 提前期（天）
    costs_per_shipment: float
    transport_costs_per_pallet: float
    transport_costs_per_ftl: float
    free_capacity_excluding: float   # 不含 TFC 的剩余产能（%）
    free_capacity_including: float   # 含 TFC 的剩余产能（%）
    basic_contract_index: float
    certification: bool

# 供应商列表：每条记录为一个字典（按游戏界面字段整理）
# 新增供应商时，复制 Merk Pak 的字典结构并修改各字段即可
SUPPLIERS: list[SupplierInfo] = [
    {
        "name": "Merk Pak",
        "product_range": "Pack",
        "country": "Germany",
        "market_share": 2.0,
        "start_payment_term": "When ordering",
        "lead_time": 7,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 29.00,
        "transport_costs_per_ftl": 725.00,
        "free_capacity_excluding": 31.0,
        "free_capacity_including": 29.0,
        "basic_contract_index": 1.0100,
        "certification": True,
    },
    {
        "name": "Boxed In",
        "product_range": "Pack",
        "country": "The Netherlands",
        "market_share": 2.0,
        "start_payment_term": "When ordering",
        "lead_time": 5,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 27.00,
        "transport_costs_per_ftl": 675.00,
        "free_capacity_excluding": 25.0,
        "free_capacity_including": 20.0,
        "basic_contract_index": 1.0000,
        "certification": False,
    },
    {
        "name": "Carton Garçon",
        "product_range": "Pack",
        "country": "Belgium",
        "market_share": 1.0,
        "start_payment_term": "At delivery",
        "lead_time": 5,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 30.00,
        "transport_costs_per_ftl": 750.00,
        "free_capacity_excluding": 26.0,
        "free_capacity_including": 21.0,
        "basic_contract_index": 0.8500,
        "certification": True,
    },
    {
        "name": "Tight",
        "product_range": "Pack",
        "country": "The Netherlands",
        "market_share": 1.0,
        "start_payment_term": "When ordering",
        "lead_time": 5,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 27.00,
        "transport_costs_per_ftl": 675.00,
        "free_capacity_excluding": 15.0,
        "free_capacity_including": 11.0,
        "basic_contract_index": 0.9800,
        "certification": False,
    },
    {
        "name": "AA Packs",
        "product_range": "Pack",
        "country": "The Netherlands",
        "market_share": 3.0,
        "start_payment_term": "At delivery",
        "lead_time": 4,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 29.00,
        "transport_costs_per_ftl": 725.00,
        "free_capacity_excluding": 12.0,
        "free_capacity_including": 10.0,
        "basic_contract_index": 0.9800,
        "certification": False,
    },
    {
        "name": "Rapid Pack",
        "product_range": "Pack",
        "country": "Germany",
        "market_share": 2.0,
        "start_payment_term": "When ordering",
        "lead_time": 10,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 27.00,
        "transport_costs_per_ftl": 675.00,
        "free_capacity_excluding": 22.0,
        "free_capacity_including": 19.0,
        "basic_contract_index": 1.0200,
        "certification": True,
    },
    # --- PET ---
    {
        "name": "Pété",
        "product_range": "PET",
        "country": "Italy",
        "market_share": 10.0,
        "start_payment_term": "At delivery",
        "lead_time": 10,
        "costs_per_shipment": 200.00,
        "transport_costs_per_pallet": 38.00,
        "transport_costs_per_ftl": 950.00,
        "free_capacity_excluding": 12.0,
        "free_capacity_including": 8.0,
        "basic_contract_index": 0.9800,
        "certification": True,
    },
    {
        "name": "Transparant",
        "product_range": "PET",
        "country": "Luxembourg",
        "market_share": 15.0,
        "start_payment_term": "When ordering",
        "lead_time": 5,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 32.00,
        "transport_costs_per_ftl": 800.00,
        "free_capacity_excluding": 25.0,
        "free_capacity_including": 10.0,
        "basic_contract_index": 1.0100,
        "certification": True,
    },
    {
        "name": "L'astique",
        "product_range": "PET",
        "country": "France",
        "market_share": 17.0,
        "start_payment_term": "At delivery",
        "lead_time": 10,
        "costs_per_shipment": 250.00,
        "transport_costs_per_pallet": 40.00,
        "transport_costs_per_ftl": 1000.00,
        "free_capacity_excluding": 10.0,
        "free_capacity_including": 2.0,
        "basic_contract_index": 0.9500,
        "certification": False,
    },
    # --- Capsule ---
    {
        "name": "Golden Cups",
        "product_range": "Capsule",
        "country": "Belgium",
        "market_share": 10.0,
        "start_payment_term": "When ordering",
        "lead_time": 5,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 30.00,
        "transport_costs_per_ftl": 750.00,
        "free_capacity_excluding": 12.0,
        "free_capacity_including": 8.0,
        "basic_contract_index": 1.0500,
        "certification": True,
    },
    {
        "name": "Copado",
        "product_range": "Capsule",
        "country": "United States",
        "market_share": 15.0,
        "start_payment_term": "At delivery",
        "lead_time": 25,
        "costs_per_shipment": 200.00,
        "transport_costs_per_pallet": 52.00,
        "transport_costs_per_ftl": 1300.00,
        "free_capacity_excluding": 30.0,
        "free_capacity_including": 25.0,
        "basic_contract_index": 1.0000,
        "certification": True,
    },
    {
        "name": "Cuckoo Cups",
        "product_range": "Capsule",
        "country": "China",
        "market_share": 4.0,
        "start_payment_term": "At delivery",
        "lead_time": 26,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 30.00,
        "transport_costs_per_ftl": 750.00,
        "free_capacity_excluding": 20.0,
        "free_capacity_including": 16.0,
        "basic_contract_index": 0.9500,
        "certification": False,
    },
    # --- Bag ---
    {
        "name": "Sacs à Dos",
        "product_range": "Bag",
        "country": "France",
        "market_share": 10.0,
        "start_payment_term": "When ordering",
        "lead_time": 6,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 30.00,
        "transport_costs_per_ftl": 750.00,
        "free_capacity_excluding": 12.0,
        "free_capacity_including": 8.0,
        "basic_contract_index": 0.9500,
        "certification": False,
    },
    {
        "name": "Bag Ete",
        "product_range": "Bag",
        "country": "Canada",
        "market_share": 15.0,
        "start_payment_term": "At delivery",
        "lead_time": 16,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 27.00,
        "transport_costs_per_ftl": 675.00,
        "free_capacity_excluding": 30.0,
        "free_capacity_including": 25.0,
        "basic_contract_index": 0.9500,
        "certification": True,
    },
    {
        "name": "Happy Bag",
        "product_range": "Bag",
        "country": "China",
        "market_share": 4.0,
        "start_payment_term": "When ordering",
        "lead_time": 25,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 38.00,
        "transport_costs_per_ftl": 950.00,
        "free_capacity_excluding": 20.0,
        "free_capacity_including": 16.0,
        "basic_contract_index": 1.0000,
        "certification": True,
    },
    {
        "name": "Satchel",
        "product_range": "Bag",
        "country": "Germany",
        "market_share": 6.0,
        "start_payment_term": "At delivery",
        "lead_time": 5,
        "costs_per_shipment": 400.00,
        "transport_costs_per_pallet": 60.00,
        "transport_costs_per_ftl": 1500.00,
        "free_capacity_excluding": 28.0,
        "free_capacity_including": 24.0,
        "basic_contract_index": 1.0000,
        "certification": True,
    },
    {
        "name": "Pouch",
        "product_range": "Bag",
        "country": "Germany",
        "market_share": 2.0,
        "start_payment_term": "When ordering",
        "lead_time": 7,
        "costs_per_shipment": 320.00,
        "transport_costs_per_pallet": 66.00,
        "transport_costs_per_ftl": 1650.00,
        "free_capacity_excluding": 10.0,
        "free_capacity_including": 6.0,
        "basic_contract_index": 1.0500,
        "certification": False,
    },
    {
        "name": "Guci",
        "product_range": "Bag",
        "country": "Italy",
        "market_share": 1.0,
        "start_payment_term": "At delivery",
        "lead_time": 7,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 27.00,
        "transport_costs_per_ftl": 675.00,
        "free_capacity_excluding": 25.0,
        "free_capacity_including": 20.0,
        "basic_contract_index": 1.0500,
        "certification": True,
    },
    # --- Orange ---
    {
        "name": "Laranja Grande",
        "product_range": "Orange",
        "country": "Brazil",
        "market_share": 25.0,
        "start_payment_term": "When ordering",
        "lead_time": 40,
        "costs_per_shipment": 200.00,
        "transport_costs_per_pallet": 55.00,
        "transport_costs_per_ftl": 1375.00,
        "free_capacity_excluding": 25.0,
        "free_capacity_including": 20.0,
        "basic_contract_index": 1.0100,
        "certification": True,
    },
    {
        "name": "Squeeze",
        "product_range": "Orange",
        "country": "United States",
        "market_share": 22.0,
        "start_payment_term": "When ordering",
        "lead_time": 25,
        "costs_per_shipment": 200.00,
        "transport_costs_per_pallet": 52.00,
        "transport_costs_per_ftl": 1300.00,
        "free_capacity_excluding": 15.0,
        "free_capacity_including": 5.0,
        "basic_contract_index": 0.9500,
        "certification": True,
    },
    # --- Mango（两种运输方式拆成两条记录）---
    {
        "name": "Bio Mango",
        "product_range": "Mango",
        "country": "Burkina Faso",
        "market_share": 2.0,
        "start_payment_term": "At delivery",
        "lead_time": 30,
        "costs_per_shipment": 200.00,
        "transport_costs_per_pallet": 63.00,
        "transport_costs_per_ftl": 1575.00,
        "free_capacity_excluding": 5.0,
        "free_capacity_including": 3.0,
        "basic_contract_index": 0.9600,
        "certification": False,
    },
    {
        "name": "Sabrosa Fresca (Truck)",
        "product_range": "Mango",
        "country": "Spain",
        "market_share": 1.0,
        "start_payment_term": "When ordering",
        "lead_time": 10,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 45.00,
        "transport_costs_per_ftl": 1125.00,
        "free_capacity_excluding": 9.0,
        "free_capacity_including": 4.0,
        "basic_contract_index": 1.2500,
        "certification": True,
    },
    {
        "name": "Sabrosa Fresca (Boat)",
        "product_range": "Mango",
        "country": "Spain",
        "market_share": 1.0,
        "start_payment_term": "When ordering",
        "lead_time": 20,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 30.00,
        "transport_costs_per_ftl": 750.00,
        "free_capacity_excluding": 9.0,
        "free_capacity_including": 4.0,
        "basic_contract_index": 1.2500,
        "certification": True,
    },
    {
        "name": "Mr. Mango",
        "product_range": "Mango",
        "country": "Congo",
        "market_share": 3.0,
        "start_payment_term": "When ordering",
        "lead_time": 35,
        "costs_per_shipment": 200.00,
        "transport_costs_per_pallet": 60.00,
        "transport_costs_per_ftl": 1500.00,
        "free_capacity_excluding": 5.0,
        "free_capacity_including": 2.0,
        "basic_contract_index": 0.9800,
        "certification": False,
    },
    {
        "name": "Home Grown",
        "product_range": "Mango",
        "country": "Nigeria",
        "market_share": 4.0,
        "start_payment_term": "When ordering",
        "lead_time": 30,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 57.00,
        "transport_costs_per_ftl": 1425.00,
        "free_capacity_excluding": 9.0,
        "free_capacity_including": 4.0,
        "basic_contract_index": 0.9500,
        "certification": False,
    },
    {
        "name": "Fruta del Sol (Truck)",
        "product_range": "Mango",
        "country": "Spain",
        "market_share": 1.0,
        "start_payment_term": "When ordering",
        "lead_time": 10,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 40.00,
        "transport_costs_per_ftl": 1000.00,
        "free_capacity_excluding": 8.0,
        "free_capacity_including": 4.0,
        "basic_contract_index": 1.2500,
        "certification": True,
    },
    {
        "name": "Fruta del Sol (Boat)",
        "product_range": "Mango",
        "country": "Spain",
        "market_share": 1.0,
        "start_payment_term": "When ordering",
        "lead_time": 20,
        "costs_per_shipment": 200.00,
        "transport_costs_per_pallet": 30.00,
        "transport_costs_per_ftl": 750.00,
        "free_capacity_excluding": 8.0,
        "free_capacity_including": 4.0,
        "basic_contract_index": 1.2500,
        "certification": True,
    },
    {
        "name": "Domanga",
        "product_range": "Mango",
        "country": "Brazil",
        "market_share": 3.0,
        "start_payment_term": "At delivery",
        "lead_time": 40,
        "costs_per_shipment": 200.00,
        "transport_costs_per_pallet": 57.00,
        "transport_costs_per_ftl": 1425.00,
        "free_capacity_excluding": 8.0,
        "free_capacity_including": 4.0,
        "basic_contract_index": 1.0000,
        "certification": True,
    },
    # --- Vitamin C（两种运输方式拆成两条记录）---
    {
        "name": "L'asco",
        "product_range": "Vitamin C",
        "country": "France",
        "market_share": 3.0,
        "start_payment_term": "At delivery",
        "lead_time": 5,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 40.00,
        "transport_costs_per_ftl": 1000.00,
        "free_capacity_excluding": 50.0,
        "free_capacity_including": 45.0,
        "basic_contract_index": 1.2000,
        "certification": True,
    },
    {
        "name": "C Plus Plus",
        "product_range": "Vitamin C",
        "country": "India",
        "market_share": 1.0,
        "start_payment_term": "At delivery",
        "lead_time": 30,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 75.00,
        "transport_costs_per_ftl": 1875.00,
        "free_capacity_excluding": 28.0,
        "free_capacity_including": 25.0,
        "basic_contract_index": 0.7500,
        "certification": True,
    },
    {
        "name": "Pop C",
        "product_range": "Vitamin C",
        "country": "China",
        "market_share": 1.0,
        "start_payment_term": "When ordering",
        "lead_time": 45,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 80.00,
        "transport_costs_per_ftl": 2000.00,
        "free_capacity_excluding": 52.0,
        "free_capacity_including": 50.0,
        "basic_contract_index": 0.7500,
        "certification": False,
    },
    {
        "name": "Novarcis",
        "product_range": "Vitamin C",
        "country": "Bangladesh",
        "market_share": 2.0,
        "start_payment_term": "When ordering",
        "lead_time": 35,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 74.00,
        "transport_costs_per_ftl": 1850.00,
        "free_capacity_excluding": 30.0,
        "free_capacity_including": 29.0,
        "basic_contract_index": 0.7500,
        "certification": False,
    },
    {
        "name": "Dose (Truck)",
        "product_range": "Vitamin C",
        "country": "United Kingdom",
        "market_share": 2.0,
        "start_payment_term": "At delivery",
        "lead_time": 10,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 36.00,
        "transport_costs_per_ftl": 900.00,
        "free_capacity_excluding": 30.0,
        "free_capacity_including": 29.0,
        "basic_contract_index": 1.2000,
        "certification": False,
    },
    {
        "name": "Dose (Boat)",
        "product_range": "Vitamin C",
        "country": "United Kingdom",
        "market_share": 2.0,
        "start_payment_term": "At delivery",
        "lead_time": 15,
        "costs_per_shipment": 160.00,
        "transport_costs_per_pallet": 30.00,
        "transport_costs_per_ftl": 750.00,
        "free_capacity_excluding": 30.0,
        "free_capacity_including": 29.0,
        "basic_contract_index": 1.2000,
        "certification": False,
    },
    {
        "name": "Caro",
        "product_range": "Vitamin C",
        "country": "Germany",
        "market_share": 2.0,
        "start_payment_term": "When ordering",
        "lead_time": 5,
        "costs_per_shipment": 250.00,
        "transport_costs_per_pallet": 34.00,
        "transport_costs_per_ftl": 850.00,
        "free_capacity_excluding": 30.0,
        "free_capacity_including": 29.0,
        "basic_contract_index": 1.2000,
        "certification": True,
    },
]

# 按供应商名称快速查询：SUPPLIERS_BY_NAME["Merk Pak"]
SUPPLIERS_BY_NAME: dict[str, SupplierInfo] = {
    supplier["name"]: supplier for supplier in SUPPLIERS
}


class Purchase_contract:
    def __init__(self, 
                 material_type, 
                 supplier_name, 
                 s_c_i, 
                 quality, 
                 lead_time,
                 certification, 
                 country, 
                 transport_mode, 
                 free_capacity, 
                 payment_term,
                 trade_unit, 
                 agreed_delivery_reliability, 
                 delivery_window,
                 supplier_development, 
                 vmi_supplier):
        '''basic information'''
        self.material_type = material_type
        self.supplier_name = supplier_name

        '''supplier contract information'''
        self.s_c_i = s_c_i #supplier contract index
        self.quality = quality
        self.lead_time = lead_time
        self.certification = certification
        self.country = country
        self.transport_mode = transport_mode
        self.free_capacity = free_capacity
        self.payment_term = payment_term
        self.trade_unit = trade_unit
        self.agreed_delivery_reliability = agreed_delivery_reliability
        self.delivery_window = delivery_window

        '''collaboration projects'''
        self.supplier_development = supplier_development
        self.vmi_supplier = vmi_supplier
        
    def generate_logistics_order():
        #todo: 从外部传入订单信息，计算得出到货时间和实际送货量。
        pass
